apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jsnorth/j-s-neurath:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jsnorth/j-s-neurath:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: j-s-neurath
        chartPath: charts/j-s-neurath
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jsnorth/j-s-neurath"
          image.tag: "{{.TAG}}"
